spring.application.name=property-management
server.port= 8085
logging.level.org.springframework.web=DEBUG

#Setup H2 Database properties
#Allow H2 database to be accesed via browser and via Java Application
spring.h2.console.enabled = true
#Database server path
spring.h2.console.path=/h2-console
#DB url and DB name (pmsdb)
#H2Database can be configured InMemory or file based, here we have taken files based approach
spring.datasource.url=jdbc:h2:file:~/h2/pmsdb
#spring.datasource.url=jdbc:h2:mem:testdb
#DB Username
spring.datasource.username=sa
#DB Password
spring.datasource.password=
#DB Driver
spring.datasource.driverClassName = org.h2.Driver
spring.jpa.hibernate.ddl-auto = update
#Enable printing of SQL queries
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect









