#active profile
spring.profiles.active=dev

# Set logging level
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG

# Log file configuration
logging.file.name=logs/spring-boot-application.log

# Console log pattern
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# File log pattern
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
